"""
Classic Articles Module — Deep Reading Edition v3
Real articles from publicly accessible sources (The Guardian).
Each article includes:
- 25+ vocabulary items with linguistics-oriented analysis
- 10+ phrase annotations
- 8+ complex sentence breakdowns with highlight_key for in-article highlighting
"""

CLASSIC_ARTICLES = [
    # ═══════════════════════════════════════════════════════════
    # ARTICLE 1 — The Guardian (Opinion / Social Policy)
    # Real article by John Kampfner, published 14 May 2026
    # ═══════════════════════════════════════════════════════════
    {
        "title": "For Three Years I Scoured the World for Answers to Europe's Big Problems – Here's What I Found",
        "source": "The Guardian",
        "source_icon": "📰",
        "category": "editorial",
        "category_label": "社论评论",
        "summary": "Japan and Taiwan have enviable care systems because they had the courage to plan. Some solutions are radical, most are hiding in plain sight. A look at what mainstream European politicians can learn from global best practice.",
        "link": "https://www.theguardian.com/commentisfree/2026/may/14/europe-big-problems-japan-taiwan-care-systems",
        "published": "2026-05-14",
        "has_full_text": True,
        "full_text": """It's mid-afternoon in Fujisawa. Schoolchildren, rucksacks on their backs, bound into a room where a group of pensioners welcome them boisterously, before sitting them down to help with their homework. This group of older people is looked after by some of the pupils' parents. Up the road, a cluster of university students live above some over-75s. They get half-price rent in return for checking in on them on their way to and from studies.

This multigenerational community I visited in a small town not far from the port of Yokohama is one of 5,000 in Japan.

Sometimes the solutions to the big social challenges of the day are right in front of us; they don't necessarily cost much, but they do require forward thinking and a determination to make them work. Across Europe, these challenges are often shirked.

By 2050, the number of centenarians in Japan could reach almost half a million. The proportion of pensioners is expected to rise to nearly 40%. In some ways, Japan is a victim of its own success, with the world's highest life expectancy for the past four decades. It is now 87 for women and 81 for men.

Japan has also shown that if you can't avoid a problem, you might as well confront it. Back in 2000, it introduced the long-term care insurance system, one of the first countries to develop such a public scheme. It is transparent and easy to navigate. Everyone knows what they must pay and when. Its purpose is to "maintain dignity and an independent daily life routine according to each person's level of abilities".

The emphasis is on giving people more of a say in where and how they are cared for. Rather than elderly people receiving services that are assigned by the state, they are encouraged to choose and contract the services themselves.

For three years, I scoured the world for best practice in addressing the big present and future challenges. The 10 countries and cities I visited, from Japan to Morocco and India to Austria, had some surprising solutions; some were radical, others were simply the product of better organisation.

What the disparate destinations I studied had in common were resilience, imagination and political courage — qualities that mainstream politicians in Europe have long struggled to demonstrate. And they seem allergic to the other precondition for securing lasting change: serious long-term planning.

With ageing populations, many European economies are creaking under the strain of funding pensions, care services and health. Yet the two areas where European governments remain most politically timid are social care and health reform. All suffer from a lack of doctors, nurses and other care professionals.

Until recently, France was cited as an example of healthcare success, but the highly centralised system disincentivises doctors and nurses from working in disadvantaged regions — so-called health deserts.

By contrast, Sweden, which has a more decentralised approach, continues to overperform. Spain's success might be seen as more surprising, with one of the highest life expectancies in Europe. It has a universal national system, which, like Britain's NHS, is free at the point of delivery, but it is run by its 17 autonomous regions, not by a central monolith.

Japan and Taiwan, as I discovered, started preparing for the demographic challenge decades ago. Taiwan's national health insurance, unlike Britain's NHS, is quick, efficient and highly digitised. Medical literacy and patient autonomy are paramount; everyone learns about diet and exercise from a young age, part of a whole-society approach to "owning" your own health. Alongside speed of delivery, the other remarkable aspect of this system is the cost. At around 8% of GDP, it is far cheaper than the European average of 10%-12%.

Some politicians say all this is impossible. They insist they would be punished for asking voters to endure short-term pain, and that the gains would be enjoyed by successor governments. Yet many examples show the opposite: when a policy is presented transparently, when other political parties are invited to input, and when voters are included in the conversation, they are more likely to accept change.

Everywhere you look, you see liberal democratic leaders paralysed with fear. They worry about the markets; they fret about conventional media and social media. They wait for bad things to happen, trying to anticipate what their critics might say of them in case they put a foot out of line. It's a self-fulfilling spiral.

Mainstream parties agonise about tacking to the left or the right. About whether to spend more on public services or slash them; to privatise or nationalise; or to clamp down further on immigration. These are the wrong questions.

Instead, they should do something different — exercise humility, find some curiosity and learn from others. Across all areas of policy, and in all parts of the world, there are examples of good practice: how to build an education system that meets the skills challenge posed by AI; how to provide equitable housing; how to create a sustainable environment and simultaneously boost growth.

Think of it another way. Consider the political developments in London, Paris and Berlin: given that the link between delivery and trust has been undermined, if mainstream politicians don't think more imaginatively about the future, they won't have a future.""",

        "annotations_vocab": [
            {"word": "boisterously", "phonetic": "/ˈbɔɪ.stər.əs.li/", "pos": "adv.", "definition": "in a noisy, energetic, and cheerful way", "chinese": "热闹地，喧闹地",
             "linguistics": "来自 boisterous（喧闹的）+ -ly。boisterous 源自中古英语 boistous（粗鲁的），后来语义正面化，从「粗鲁」变为「充满活力的喧闹」。这种语义演变（semantic amelioration）在英语中很常见，如 nice 原义是「无知的」。",
             "usage": "通用词，写作口语皆可。口语替代：loudly and happily / with a lot of energy。搭配：boisterous crowd / laughter / children / welcome。",
             "examples": [{"text": "The children played boisterously in the garden after school.", "source": "Cambridge Dictionary"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "multigenerational", "phonetic": "/ˌmʌl.ti.dʒen.əˈreɪ.ʃən.əl/", "pos": "adj.", "definition": "involving or relating to several generations of a family or community", "chinese": "多代的，跨世代的",
             "linguistics": "multi-（多）+ generation（代）+ -al（形容词后缀）。这是英语复合造词法的典型案例。掌握 multi- 前缀可以理解大量类似词：multicultural（多元文化的）、multilateral（多边的）、multimedia（多媒体）。",
             "usage": "半正式，社会政策和人口学常用。口语中可以说 involving people of all ages / mixing old and young。搭配：multigenerational household / community / living。",
             "examples": [{"text": "Multigenerational households are becoming more common in urban areas.", "source": "The Economist, 2023"}],
             "level": "IELTS 7.0+"},
            {"word": "shirked", "phonetic": "/ʃɜːkt/", "pos": "v.", "definition": "to avoid or neglect a duty or responsibility", "chinese": "逃避，推卸（责任）",
             "linguistics": "可能源自德语 Schurke（无赖）。shirk 专门用于「逃避责任/义务」，暗含道德批判——不是不能做，而是不愿做。名词形式 shirker（逃避责任的人）在一战时指逃避服兵役者。",
             "usage": "半正式。口语替代：avoid / dodge / duck / get out of。搭配：shirk responsibility / duty / obligation / the issue。",
             "examples": [{"text": "He was accused of shirking his responsibilities as a manager.", "source": "Collins English Dictionary"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "centenarians", "phonetic": "/ˌsen.tɪˈneə.ri.ənz/", "pos": "n.", "definition": "people who are 100 years old or more", "chinese": "百岁老人",
             "linguistics": "centenary（百年纪念）+ -an（表示人）。词根 cent- 来自拉丁语 centum（一百）。同根词系列：century（世纪）、centimetre（厘米）、percent（百分比）、centurion（百夫长）。掌握 cent- 词根可以推断许多相关词汇。",
             "usage": "正式用语。口语中说 people over a hundred / people who've lived past 100。常见于人口统计和健康领域。",
             "examples": [{"text": "Japan has more centenarians per capita than any other country.", "source": "WHO Report, 2023"}],
             "level": "IELTS 7.0+"},
            {"word": "transparent", "phonetic": "/trænsˈpær.ənt/", "pos": "adj.", "definition": "open to public scrutiny; easy to understand; without hidden agenda", "chinese": "透明的，公开的",
             "linguistics": "trans-（穿过）+ parere（出现）+ -ent。字面义「能看穿的」。双义词：物理义（透明的玻璃）和比喻义（政策透明、信息公开）。本文使用比喻义。反义词 opaque 同样有双重含义。",
             "usage": "通用词。口语替代：open / clear / upfront / nothing to hide。搭配：transparent process / policy / government / system。",
             "examples": [{"text": "The company promised to be more transparent about its environmental impact.", "source": "Financial Times, 2023"}],
             "level": "CET-4 / IELTS 6.0+"},
            {"word": "navigate", "phonetic": "/ˈnæv.ɪ.ɡeɪt/", "pos": "v.", "definition": "to find one's way through a complex system or situation", "chinese": "驾驭，操控，找到方向",
             "linguistics": "拉丁语 navigare（航行），navis（船）+ agere（驾驶）。原义「驾船航行」，现在广泛比喻化：navigate a system（在系统中找到方向）、navigate challenges（应对挑战）。英语中大量航海术语已经比喻化。",
             "usage": "通用词，写作口语皆可。口语替代：find your way through / deal with / work through。搭配：navigate the system / bureaucracy / challenges / complexities。",
             "examples": [{"text": "Patients often struggle to navigate the complex healthcare system.", "source": "The Guardian, 2023"}],
             "level": "CET-4 / IELTS 6.0+"},
            {"word": "disparate", "phonetic": "/ˈdɪs.pər.ət/", "pos": "adj.", "definition": "fundamentally different and distinct; not able to be compared", "chinese": "截然不同的，迥异的",
             "linguistics": "拉丁语 disparare（分开），dis-（分）+ parare（准备/等同）。与 desperate（绝望的）发音相近但含义完全不同——注意区分！disparate 强调事物之间的差异如此之大以至于难以比较。",
             "usage": "书面正式。口语替代：very different / diverse / unrelated / worlds apart。搭配：disparate groups / elements / communities / views。",
             "examples": [{"text": "The study drew participants from disparate backgrounds and cultures.", "source": "Nature, 2023"}],
             "level": "TEM-8 / IELTS 7.5+"},
            {"word": "resilience", "phonetic": "/rɪˈzɪl.i.əns/", "pos": "n.", "definition": "the ability to recover quickly from difficulties; toughness", "chinese": "韧性，恢复力",
             "linguistics": "拉丁语 resilire（弹回），re-（回）+ salire（跳）。原是物理学术语（材料受力变形后恢复原状的能力），现广泛用于心理学和社会科学。近年成为教育和心理健康领域的高频词。",
             "usage": "通用词，写作口语皆可。口语替代：toughness / bounce-back ability / grit。搭配：build resilience / show resilience / emotional resilience / community resilience。",
             "examples": [{"text": "Building resilience in children requires both support and manageable challenges.", "source": "Harvard Education Review, 2022"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "precondition", "phonetic": "/ˌpriː.kənˈdɪʃ.ən/", "pos": "n.", "definition": "something that must exist or happen before something else can happen", "chinese": "先决条件，前提",
             "linguistics": "pre-（前）+ condition（条件）。这是英语前缀造词的典型案例。掌握 pre- 前缀（= before）可以推断：prerequisite（先决条件）、predetermined（预先确定的）、precaution（预防措施）、preview（预览）。",
             "usage": "半正式。口语替代：requirement / must-have / necessary condition。搭配：a precondition for / set preconditions / meet the preconditions。",
             "examples": [{"text": "Trust is a precondition for any successful negotiation.", "source": "Foreign Affairs, 2023"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "creaking", "phonetic": "/ˈkriː.kɪŋ/", "pos": "v./adj.", "definition": "showing signs of strain or age; making harsh sounds under pressure", "chinese": "不堪重负的，吱吱作响的（比喻摇摇欲坠）",
             "linguistics": "拟声词（onomatopoeia）：模仿木头或金属在压力下发出的声音。在本文中是比喻用法：economies are creaking under the strain = 经济体在压力下像老旧木头一样吱吱作响，暗示随时可能崩溃。",
             "usage": "半正式。口语替代：struggling / under pressure / buckling / falling apart。搭配：creaking under the strain / weight / pressure。",
             "examples": [{"text": "The country's infrastructure is creaking under the weight of rapid urbanisation.", "source": "The Economist, 2023"}],
             "level": "IELTS 7.0+"},
            {"word": "timid", "phonetic": "/ˈtɪm.ɪd/", "pos": "adj.", "definition": "lacking courage or confidence; easily frightened", "chinese": "胆怯的，畏缩的",
             "linguistics": "拉丁语 timidus（害怕的），timere（恐惧）。与 intimidate（恐吓）同根——intimidate 字面义是「使人变得 timid」。注意 timid 既可描述性格（a timid person），也可描述行为（a timid response），如本文形容政府政策胆怯。",
             "usage": "通用词。口语替代：shy / scared / cautious / lacking courage。搭配：timid approach / response / leader / reform。",
             "examples": [{"text": "The government's timid response to the crisis drew widespread criticism.", "source": "Financial Times, 2023"}],
             "level": "CET-4 / IELTS 6.5+"},
            {"word": "disincentivises", "phonetic": "/ˌdɪs.ɪnˈsen.tɪ.vaɪ.zɪz/", "pos": "v.", "definition": "to discourage or deter from doing something through removing motivation", "chinese": "抑制……的积极性，起到负面激励作用",
             "linguistics": "dis-（否定/反向）+ incentive（激励）+ -ise（动词化）。三层构词：先理解 incentive（激励），加上 dis- 变成反义（去除激励），再加 -ise 变成动词。这展示了英语通过词缀层层叠加创造新词的能力。",
             "usage": "书面正式，政策讨论用语。口语替代：discourages / puts people off / makes people less likely to。搭配：disincentivise investment / work / innovation。",
             "examples": [{"text": "High marginal tax rates can disincentivise entrepreneurship.", "source": "The Economist, 2022"}],
             "level": "IELTS 7.5+"},
            {"word": "decentralised", "phonetic": "/diːˈsen.trə.laɪzd/", "pos": "adj.", "definition": "with power distributed away from a central authority to local levels", "chinese": "分权的，去中心化的",
             "linguistics": "de-（去除/反向）+ centralise（集中化）+ -d。de- 前缀表示「去除/逆转」：decode（解码）、decompose（分解）、deregulate（放松管制）。在政治学中 decentralisation（分权）与 centralisation（集权）是核心对立概念。",
             "usage": "正式用语，政治和管理学高频词。口语替代：spread out / local control / not controlled by one authority。搭配：decentralised system / government / approach / decision-making。",
             "examples": [{"text": "A decentralised approach allows local communities to address their own needs.", "source": "World Bank, 2022"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "monolith", "phonetic": "/ˈmɒn.ə.lɪθ/", "pos": "n.", "definition": "a large, impersonal, and inflexible organisation or system", "chinese": "庞然大物，铁板一块的组织",
             "linguistics": "希腊语 mono-（单一）+ lithos（石头）。原义「一块巨石」，引申为「庞大而僵化的组织」。经典科幻电影《2001太空漫游》中的黑色石碑就叫 monolith。在本文中暗指英国 NHS 的集中式体制过于庞大僵硬。",
             "usage": "半正式。口语替代：a giant / behemoth / one big thing。搭配：a corporate monolith / a bureaucratic monolith / not a monolith。",
             "examples": [{"text": "The company had become a monolith, slow to adapt to changing markets.", "source": "Harvard Business Review, 2022"}],
             "level": "TEM-8 / IELTS 7.5+"},
            {"word": "demographic", "phonetic": "/ˌdem.əˈɡræf.ɪk/", "pos": "adj.", "definition": "relating to the statistical characteristics of a population", "chinese": "人口统计学的",
             "linguistics": "希腊语 demos（人民）+ graphein（书写/记录）。demo- 这个词根很重要：democracy（民主 = 人民统治）、demography（人口学）、epidemic（流行病 = 在人民中传播）。demographic challenge = 人口结构变化带来的挑战（如老龄化）。",
             "usage": "正式用语。口语中说 population-related / age-related。搭配：demographic shift / challenge / change / trend / dividend。",
             "examples": [{"text": "Europe faces a demographic challenge as birth rates decline and populations age.", "source": "The Economist, 2023"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "digitised", "phonetic": "/ˈdɪdʒ.ɪ.taɪzd/", "pos": "adj.", "definition": "converted to or operated through digital technology", "chinese": "数字化的",
             "linguistics": "digit（数字）+ -ise（动词化）+ -d。digit 来自拉丁语 digitus（手指），因为古人用手指计数。digitise = 把信息转化为数字格式。注意英式 digitise vs 美式 digitize，经济学人/卫报用英式拼写。",
             "usage": "通用词。口语替代：digital / online / computerised / tech-based。搭配：digitised records / services / healthcare / economy。",
             "examples": [{"text": "Estonia has one of the most digitised government systems in the world.", "source": "BBC News, 2023"}],
             "level": "CET-6 / IELTS 6.5+"},
            {"word": "paramount", "phonetic": "/ˈpær.ə.maʊnt/", "pos": "adj.", "definition": "more important than anything else; supreme", "chinese": "至高无上的，最重要的",
             "linguistics": "古法语 paramont（在上面），para-（在旁边/超过）+ mont（山）。字面义「在山之上」= 最高的。注意这个词的绝对性——paramount 意味着「没有什么比这更重要」，语气非常强。",
             "usage": "半正式。口语替代：most important / top priority / number one / above all else。搭配：of paramount importance / safety is paramount / paramount concern。",
             "examples": [{"text": "Patient safety should be paramount in all healthcare decisions.", "source": "The Lancet, 2023"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "autonomy", "phonetic": "/ɔːˈtɒn.ə.mi/", "pos": "n.", "definition": "the right or condition of self-governance; independence", "chinese": "自主权，自治",
             "linguistics": "希腊语 auto-（自己）+ nomos（法律/规则）。字面义「自己给自己制定法律」。三个层次的用法：① 政治自治（regional autonomy）② 个人自主（patient autonomy）③ 组织独立（institutional autonomy）。",
             "usage": "半正式。口语替代：independence / freedom / self-control / the right to decide for yourself。搭配：regional autonomy / personal autonomy / grant autonomy。",
             "examples": [{"text": "Respecting patient autonomy is a cornerstone of modern medical ethics.", "source": "British Medical Journal, 2023"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "paralysed", "phonetic": "/ˈpær.əl.aɪzd/", "pos": "adj.", "definition": "unable to act or function; rendered completely helpless", "chinese": "瘫痪的，动弹不得的（比喻无法行动）",
             "linguistics": "希腊语 paralyein（使松弛），para-（在旁边）+ lyein（松开）。医学义：身体瘫痪。比喻义：因恐惧/犹豫而无法行动。本文用比喻义：领导人被恐惧「瘫痪」了。注意英式 paralyse vs 美式 paralyze。",
             "usage": "通用词。口语替代：frozen / stuck / unable to move / too scared to act。搭配：paralysed by fear / indecision / uncertainty。",
             "examples": [{"text": "The committee was paralysed by indecision and failed to act.", "source": "The Guardian, 2023"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "agonise", "phonetic": "/ˈæɡ.ə.naɪz/", "pos": "v.", "definition": "to worry greatly and painfully about something; to struggle with a decision", "chinese": "苦恼，焦虑不安",
             "linguistics": "希腊语 agonizesthai（竞争），agon（比赛/竞争）。agony（痛苦）、protagonist（主角 = 第一个竞争者）、antagonist（对手）都同源。agonise 比 worry 更强烈——不是普通的担心，而是痛苦地纠结。",
             "usage": "半正式。口语替代：worry a lot / stress about / overthink / lose sleep over。搭配：agonise over / about a decision / whether to...。",
             "examples": [{"text": "She agonised over whether to accept the job offer abroad.", "source": "Collins English Dictionary"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "tacking", "phonetic": "/ˈtæk.ɪŋ/", "pos": "v.", "definition": "changing course or direction (originally a sailing term)", "chinese": "改变方向，转向",
             "linguistics": "航海术语：帆船在逆风时需要之字形前进（tacking），每次转向称为一个 tack。在政治语境中比喻「改变立场/策略方向」。英语中保留了大量航海比喻：in the wake of, plain sailing, all at sea, on an even keel 等。",
             "usage": "半正式。口语替代：moving / shifting / leaning / changing direction。搭配：tacking left / right / to the centre。",
             "examples": [{"text": "The party is tacking to the right on immigration policy.", "source": "The Economist, 2023"}],
             "level": "IELTS 7.5+"},
            {"word": "equitable", "phonetic": "/ˈek.wɪ.tə.bəl/", "pos": "adj.", "definition": "fair and impartial; treating all people equally", "chinese": "公平的，公正的",
             "linguistics": "拉丁语 aequitas（公平），aequus（相等）。与 equal（相等的）同源但含义更深：equal 强调「一样」，equitable 强调「公正」。equal pay 是同工同酬，equitable distribution 是按需公正分配（不一定人人一样）。",
             "usage": "正式用语。口语替代：fair / just / balanced。搭配：equitable distribution / access / treatment / housing / society。",
             "examples": [{"text": "An equitable distribution of resources is essential for social stability.", "source": "UN Development Programme, 2023"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "sustainable", "phonetic": "/səˈsteɪ.nə.bəl/", "pos": "adj.", "definition": "able to be maintained at a certain level without depleting resources", "chinese": "可持续的",
             "linguistics": "sus-（= sub- 的变体，下面）+ tain（持有）+ -able。sustain = 从下面支撑住 = 维持。sustainable 字面义「能被持续维持的」。这个词从环保领域扩展到经济（sustainable growth）、社会（sustainable development）等多个领域。",
             "usage": "通用词。口语替代：long-lasting / green / eco-friendly / that can keep going。搭配：sustainable development / growth / energy / environment。",
             "examples": [{"text": "The company has committed to sustainable practices across its supply chain.", "source": "Financial Times, 2023"}],
             "level": "CET-4 / IELTS 6.0+"},
            {"word": "simultaneously", "phonetic": "/ˌsɪm.əlˈteɪ.ni.əs.li/", "pos": "adv.", "definition": "at the same time", "chinese": "同时地",
             "linguistics": "拉丁语 simul（同时）+ -taneous + -ly。simul 还产生了 similar（相似的）、simulate（模拟）、assimilate（同化）。simultaneously 在写作中比 at the same time 更正式精炼。",
             "usage": "通用词，但更偏书面。口语替代：at the same time / together / all at once。搭配：simultaneously pursue / achieve / address / manage。",
             "examples": [{"text": "The government must simultaneously promote growth and reduce emissions.", "source": "The Economist, 2023"}],
             "level": "CET-4 / IELTS 6.5+"},
            {"word": "imaginatively", "phonetic": "/ɪˈmædʒ.ɪ.nə.tɪv.li/", "pos": "adv.", "definition": "in a creative and original way; with imagination", "chinese": "富有想象力地，创造性地",
             "linguistics": "imagine（想象）+ -ative（形容词后缀，表示「具有……倾向的」）+ -ly。-ative 后缀系列：creative, innovative, collaborative, speculative。这些词都描述思维和行动的方式。",
             "usage": "通用词。口语替代：creatively / in a new way / with fresh ideas / outside the box。搭配：think imaginatively / respond imaginatively / imaginatively designed。",
             "examples": [{"text": "Schools need to think imaginatively about how to engage students.", "source": "The Guardian, 2023"}],
             "level": "CET-6 / IELTS 7.0+"},
        ],

        "annotations_phrases": [
            {"phrase": "right in front of us", "definition": "obvious and easy to see, yet often overlooked", "chinese": "就在眼前（却被忽视）",
             "linguistics": "字面义和比喻义的完美融合。字面义：在我们面前。比喻义：解决方案明明很明显，我们却视而不见。类似表达：hiding in plain sight（摆在明面上却没人注意到）、staring us in the face。",
             "usage": "通用词组，写作口语皆可。口语替代：obvious / staring us in the face / under our noses。常用于指出人们忽视了显而易见的事情。",
             "examples": [{"text": "The answer was right in front of us the whole time.", "source": "Oxford Dictionary of Idioms"}],
             "level": "CET-4 / IELTS 5.5+"},
            {"phrase": "forward thinking", "definition": "planning for the future; being proactive rather than reactive", "chinese": "前瞻性思维",
             "linguistics": "forward（向前）+ thinking（思考）。复合形容词。对比：forward-thinking（有前瞻性的）vs backward-looking（守旧的）。注意做定语时加连字符：a forward-thinking approach。",
             "usage": "半正式。口语替代：planning ahead / thinking about the future / being proactive。搭配：forward-thinking approach / leader / policy / company。",
             "examples": [{"text": "The city adopted a forward-thinking approach to urban planning.", "source": "The Guardian, 2023"}],
             "level": "CET-6 / IELTS 6.5+"},
            {"phrase": "a victim of its own success", "definition": "suffering negative consequences that result from one's achievements", "chinese": "自身成功的牺牲品（成功带来了新问题）",
             "linguistics": "悖论表达：success（成功）通常是正面的，victim（受害者）是负面的，放在一起产生矛盾效果。日本因为医疗成功导致人均寿命极高，反而面临老龄化危机。这种表达在社论中非常常见。",
             "usage": "半正式，写作口语皆可。口语替代：too successful for its own good / success backfired。用于描述成功带来的意外负面后果。",
             "examples": [{"text": "The app became a victim of its own success, crashing under the weight of too many users.", "source": "TechCrunch, 2023"}],
             "level": "IELTS 7.0+"},
            {"phrase": "might as well", "definition": "used to suggest doing something because there is no reason not to", "chinese": "不妨，索性",
             "linguistics": "这个短语表示「既然避免不了，那就直接面对吧」，暗含一种务实的接受态度。比 should 语气更随意，比 must 压力更小。是日常英语中极高频的表达。",
             "usage": "通用，口语更常见。搭配：might as well do it / try / go / accept。注意 might as well 后面直接跟动词原形。",
             "examples": [{"text": "If we can't change the situation, we might as well make the best of it.", "source": "Longman Dictionary"}],
             "level": "CET-4 / IELTS 5.5+"},
            {"phrase": "more of a say", "definition": "a greater degree of influence or involvement in decision-making", "chinese": "更大的发言权/决策参与度",
             "linguistics": "say 在这里不是动词而是名词，意为「发言权/意见」。have a say in = 在某事上有发言权。more of a say = 更大的话语权。这是英语中动词名词化的典型案例。类似用法：have a go / have a look / have a try。",
             "usage": "通用。口语中非常常见。搭配：have a say in / have more of a say / give people a say。",
             "examples": [{"text": "Workers should have more of a say in how the company is run.", "source": "The Guardian, 2023"}],
             "level": "CET-4 / IELTS 6.0+"},
            {"phrase": "creaking under the strain", "definition": "struggling badly under excessive pressure or demands", "chinese": "在重压下不堪重负",
             "linguistics": "具象比喻：想象一座老旧的木桥在重压下发出吱吱声（creaking），随时可能断裂。strain 是「压力/负担」。整个短语传达出系统即将崩溃的画面感。比 under pressure 更生动，暗示问题比表面看起来严重。",
             "usage": "半正式，新闻写作常用。口语替代：struggling / under huge pressure / about to break / can't cope。",
             "examples": [{"text": "The prison system is creaking under the strain of overcrowding.", "source": "BBC News, 2023"}],
             "level": "IELTS 7.0+"},
            {"phrase": "free at the point of delivery", "definition": "services that users do not pay for directly when they receive them", "chinese": "使用时免费（由税收等其他方式支付）",
             "linguistics": "这是描述英国 NHS（国民健康服务）最经典的短语。point of delivery = 服务交付的时刻。free at the point of delivery ≠ completely free（不是完全免费——通过税收已经间接支付了）。理解这个概念对理解福利国家体制至关重要。",
             "usage": "正式，政策讨论专用。口语替代：free when you use it / you don't pay when you go。主要用于讨论公共服务（尤其是医疗）。",
             "examples": [{"text": "The principle that the NHS should remain free at the point of delivery is widely supported.", "source": "The Guardian, 2023"}],
             "level": "IELTS 7.0+"},
            {"phrase": "put a foot out of line", "definition": "to do something wrong or inappropriate; to deviate from expected behaviour", "chinese": "行差踏错，越规矩",
             "linguistics": "想象军队列队行进，有人踏出了队列（foot out of line）= 违反纪律/规矩。暗含的意思是：政客们小心翼翼，生怕做错一步被批评。展现了本文对政治家胆怯行为的讽刺。",
             "usage": "半正式。口语替代：do something wrong / step out of line / make a mistake / cross the line。搭配：不敢 put a foot out of line / anyone who puts a foot out of line。",
             "examples": [{"text": "Staff are afraid to put a foot out of line for fear of being fired.", "source": "Collins English Dictionary"}],
             "level": "IELTS 7.0+"},
            {"phrase": "self-fulfilling spiral", "definition": "a cycle where expectations or fears cause the very outcome that was feared", "chinese": "自我实现的恶性循环",
             "linguistics": "结合了两个概念：self-fulfilling prophecy（自我实现的预言——你怕什么就来什么）和 downward spiral（螺旋式下降）。政客害怕做决定 → 不做决定导致问题恶化 → 被批评 → 更加不敢做决定。作者用一个短语概括了整个恶性循环。",
             "usage": "书面正式。口语替代：vicious cycle / things keep getting worse / a doom loop。用于描述无法打破的负面循环。",
             "examples": [{"text": "Negative thinking can become a self-fulfilling spiral of anxiety and avoidance.", "source": "Psychology Today, 2023"}],
             "level": "IELTS 7.5+"},
            {"phrase": "clamp down on", "definition": "to take strict action to stop or limit something", "chinese": "严厉打击，加强管控",
             "linguistics": "clamp（夹钳）+ down（下去）= 用夹钳牢牢夹住 = 严厉控制。非常生动的动词短语。名词形式：crackdown（大写）。与 crack down on 近义，但 clamp down 更强调「控制/限制」，crack down 更强调「惩罚」。",
             "usage": "通用，写作口语皆可。口语替代：get tough on / crack down on / tighten up on。搭配：clamp down on crime / immigration / spending / dissent。",
             "examples": [{"text": "Authorities have vowed to clamp down on tax evasion.", "source": "Financial Times, 2023"}],
             "level": "CET-6 / IELTS 6.5+"},
        ],

        "annotations_sentences": [
            {"sentence": "Sometimes the solutions to the big social challenges of the day are right in front of us; they don't necessarily cost much, but they do require forward thinking and a determination to make them work.",
             "highlight_key": "Sometimes the solutions to the big social challenges of the day are right in front of us",
             "translation": "有时候，解决当今重大社会挑战的方案就在我们眼前；它们不一定花费很多，但确实需要前瞻性思维和使之奏效的决心。",
             "breakdown": "分号前：Sometimes the solutions（有时候解决方案）→ to the big social challenges of the day（当今重大社会挑战的）→ are right in front of us（就在我们眼前）。分号后：they don't necessarily cost much（不一定花费很多）→ but they do require（但确实需要）→ forward thinking and a determination to make them work（前瞻性思维和决心）。do 在这里是强调助动词。",
             "grammar_points": ["分号连接两个密切相关的独立分句", "do require 中的 do 是强调用法（emphatic do）", "of the day = 当今的、当下的"],
             "writing_tip": "这个句式可以用来提出一个反直觉的论点：The solutions to X are not Y, but Z. 雅思示例：The solutions to urban congestion don't necessarily involve building more roads, but they do require rethinking how we use public space."},
            {"sentence": "In some ways, Japan is a victim of its own success, with the world's highest life expectancy for the past four decades.",
             "highlight_key": "In some ways, Japan is a victim of its own success, with the world's highest life expectancy for the past four decades",
             "translation": "从某种意义上说，日本是自身成功的牺牲品——过去四十年来它拥有世界最高的预期寿命。",
             "breakdown": "In some ways（在某些方面）限定了这个说法的适用范围 → Japan is a victim of its own success（日本是自身成功的受害者——悖论表达）→ with the world's highest life expectancy（用 with 短语补充具体说明「成功」是什么）→ for the past four decades（时间状语）。",
             "grammar_points": ["in some ways 作为限定语，避免绝对化", "with + 名词 作为伴随状语补充说明", "victim of its own success 是固定搭配/习语"],
             "writing_tip": "In some ways, X is a victim of its own success 适用于任何成功导致新问题的场景。雅思示例：In some ways, social media is a victim of its own success — its very ubiquity has made it a source of anxiety."},
            {"sentence": "What the disparate destinations I studied had in common were resilience, imagination and political courage — qualities that mainstream politicians in Europe have long struggled to demonstrate.",
             "highlight_key": "What the disparate destinations I studied had in common were resilience, imagination and political courage",
             "translation": "我研究的这些截然不同的目的地有一个共同点：韧性、想象力和政治勇气——这些品质正是欧洲主流政客长期以来难以展现的。",
             "breakdown": "What 引导主语从句 → the disparate destinations I studied（我研究的截然不同的目的地）→ had in common（共同拥有的）→ were（系动词）→ resilience, imagination and political courage（三个名词并列）→ 破折号后补充：qualities that...（定语从句修饰 qualities）→ mainstream politicians have long struggled to demonstrate（主流政客长期难以展示的）。",
             "grammar_points": ["What 引导名词性从句做主语", "had in common = 共有的特征", "破折号后的同位语从句补充说明", "have long struggled to = 长期以来一直难以"],
             "writing_tip": "What X and Y have in common is Z — qualities that... 这个句式适合总结发现。雅思示例：What all successful education systems have in common is investment in teachers — a commitment that many governments have failed to make."},
            {"sentence": "With ageing populations, many European economies are creaking under the strain of funding pensions, care services and health.",
             "highlight_key": "With ageing populations, many European economies are creaking under the strain of funding pensions, care services and health",
             "translation": "随着人口老龄化，许多欧洲经济体在养老金、护理服务和医疗保健的资金压力下不堪重负。",
             "breakdown": "With ageing populations（前置状语，交代背景/原因）→ many European economies（主语）→ are creaking under the strain（谓语：在压力下吱吱作响——拟人化比喻）→ of funding pensions, care services and health（具体说明压力来源）。creaking 这个动词将经济体比作承受重压的老旧结构物。",
             "grammar_points": ["With + 名词 短语作原因/背景状语", "creaking under the strain 是比喻修辞（personification/metaphor）", "三个名词并列列举"],
             "writing_tip": "With + 背景 + 主语 + 比喻动词 这个句式适合描述系统性困境。雅思示例：With rising inequality, many democracies are buckling under the weight of public discontent."},
            {"sentence": "Until recently, France was cited as an example of healthcare success, but the highly centralised system disincentivises doctors and nurses from working in disadvantaged regions — so-called health deserts.",
             "highlight_key": "the highly centralised system disincentivises doctors and nurses from working in disadvantaged regions",
             "translation": "直到最近，法国还被视为医疗保健成功的典范，但高度集中化的体制使得医生和护士不愿在弱势地区工作——即所谓的「医疗荒漠」。",
             "breakdown": "Until recently（时间状语：直到最近）→ France was cited as an example（法国被引用为榜样——被动语态）→ but 转折 → the highly centralised system（高度集中的体制）→ disincentivises doctors and nurses from working（抑制了医护人员的工作积极性）→ in disadvantaged regions（在弱势地区）→ 破折号引出术语解释：so-called health deserts（所谓的医疗荒漠）。",
             "grammar_points": ["Until recently + 过去时 vs but + 现在时 表示情况已经改变", "disincentivise sb from doing sth 是正式搭配", "so-called 用于引入特定术语或带有质疑的说法"],
             "writing_tip": "Until recently, X was seen as Y, but... 是一个非常好用的转折句式，适合推翻传统观点。雅思示例：Until recently, GDP growth was seen as the primary indicator of national prosperity, but this measure fails to account for inequality."},
            {"sentence": "Everywhere you look, you see liberal democratic leaders paralysed with fear.",
             "highlight_key": "Everywhere you look, you see liberal democratic leaders paralysed with fear",
             "translation": "放眼望去，你看到的都是被恐惧所瘫痪的自由民主国家领导人。",
             "breakdown": "Everywhere you look（不管你看哪里——让步状语从句）→ you see（你看到）→ liberal democratic leaders（自由民主国家领导人）→ paralysed with fear（被恐惧瘫痪——过去分词短语做补语）。这句话的力量在于简洁和夸张：用 everywhere 和 paralysed 制造戏剧效果。",
             "grammar_points": ["Everywhere you look 作让步/范围状语", "paralysed with fear 是过去分词短语做宾语补足语", "with fear 表示原因"],
             "writing_tip": "Everywhere you look, you see X 是一个有力的总结句式，表示某个现象非常普遍。雅思示例：Everywhere you look, you see the consequences of decades of underinvestment in public infrastructure."},
            {"sentence": "They wait for bad things to happen, trying to anticipate what their critics might say of them in case they put a foot out of line.",
             "highlight_key": "They wait for bad things to happen, trying to anticipate what their critics might say of them in case they put a foot out of line",
             "translation": "他们等着坏事发生，试图预判批评者可能会怎么说他们——万一他们行差踏错的话。",
             "breakdown": "They wait for bad things to happen（主句：等着坏事发生——讽刺领导人的被动态度）→ trying to anticipate（现在分词短语表伴随状态）→ what their critics might say of them（what 引导宾语从句：批评者可能会说什么）→ in case they put a foot out of line（in case 引导条件从句：以防万一他们出错）。三层嵌套展现了政客的怯懦心理。",
             "grammar_points": ["wait for sth to happen 等待某事发生", "trying to 现在分词做伴随状语", "in case 引导条件/目的状语从句", "put a foot out of line 习语：行为出格"],
             "writing_tip": "这种多层嵌套的句子非常适合描述复杂的心理过程或因果链条。注意每一层都增加了新的信息维度。"},
            {"sentence": "Consider the political developments in London, Paris and Berlin: given that the link between delivery and trust has been undermined, if mainstream politicians don't think more imaginatively about the future, they won't have a future.",
             "highlight_key": "if mainstream politicians don't think more imaginatively about the future, they won't have a future",
             "translation": "想想伦敦、巴黎和柏林的政治发展吧：鉴于执行力与公信力之间的纽带已经被削弱，如果主流政客不对未来进行更有想象力的思考，他们自己就不会有未来。",
             "breakdown": "Consider...（祈使句开头，直接要求读者行动）→ 冒号后展开论证 → given that（鉴于——让步/前提条件）→ the link between delivery and trust has been undermined（执政表现与信任之间的联系被削弱了）→ if...don't think more imaginatively（如果不更有想象力地思考）→ they won't have a future（他们自己就没有未来）。最后用 future 一词做文字游戏（think about the future / have a future）。",
             "grammar_points": ["祈使句 Consider 直接引入论点", "given that 引导让步/前提条件从句", "冒号用于引出解释", "词汇回环（future 一词两义，形成双关）"],
             "writing_tip": "用词汇回环（同一个词在句末以不同含义出现）是非常高级的修辞。雅思示例：If we don't invest in education now, we'll pay the price later — and the price will be far higher than the investment."},
        ],
    },

    # ═══════════════════════════════════════════════════════════
    # ARTICLE 2 — The Guardian (Opinion / Culture & Environment)
    # Real article by Jonathan Liew, published 13 May 2026
    # ═══════════════════════════════════════════════════════════
    {
        "title": "David Attenborough Is Not Just a National Treasure: He Is Also the Most Radical Person on TV",
        "source": "The Guardian",
        "source_icon": "📰",
        "category": "literature",
        "category_label": "文化评论",
        "summary": "The naturalist is venerated as a cuddly Paddington Bear, but he's more than that. Don't let the superficial backslaps obscure the political critique he makes about capitalism and the climate crisis.",
        "link": "https://www.theguardian.com/commentisfree/2026/may/13/david-attenborough-most-radical-person-tv",
        "published": "2026-05-13",
        "has_full_text": True,
        "full_text": """The excesses the capitalist system has brought us have got to be curbed somehow. Ordinary people worldwide are beginning to realise that greed does not actually lead to joy. Our economic system has been based on the profit principle: you have to come out at the end of the year having made a profit, and the bigger profit you have made, the better it is. In the short term that works, but it ends with disaster.

At this point, I should make a confession. The above sentiments are not mine at all. In fact, they were pilfered, purloined, shoplifted from a far more erudite radical thinker than myself. So, quiz time: which incendiary leftwing firebrand spoke these words? At the very least, you would probably assume that, in the current climate, anyone daring to utter these dangerous fringe sentiments would be cast to the margins of our cultural life, only occasionally being let out for the purposes of getting shouted at on the Jeremy Vine show.

Well, as you've probably guessed by now, it was actually the gorilla guy. The national treasure. The beloved 100-year-old television naturalist, often cited in polls as the most trusted man in the country, was also the man who advocated for seismic global financial redistribution in a 2020 BBC interview, arguing for a utopian future in which "those who have a great deal, perhaps, will have a little bit less, and those that have very little will have a little more".

And, of course, David Attenborough has been trying for many years to tell us what he actually thinks. He proudly voted remain, has railed at Michael Gove, speaks approvingly of the involvement of young people in politics and, in 2016, advocated — only partly in jest and however unwisely — the assassination of Donald Trump. He was banging on about the dangers of mass consumption, extractive capitalism and the miseries of the market economy long before Blue Planet II set footage of a plastic-choked pilot whale to mournful music. He has been warning of our manmade climate catastrophe, in increasingly shrill and alarming terms, for about two decades. The question, as he enters a frankly unbelievable 11th decade, is whether anyone is still actually prepared to listen.

Certainly, anyone watching his centenary tribute on BBC One would have struggled to reconcile the quiet radical depicted above with the cuddly senior citizen being feted on stage at the Royal Albert Hall. A galaxy of celebrities was wheeled out to deliver warm benedictions. A birthday letter from King Charles was conveyed to London by a troupe of CGI foxes and hedgehogs. Beyond some vague bromides about "protecting the planet", Attenborough's activism and worldview remained entirely hidden. The climate crisis was not mentioned once.

This is, of course, the Attenborough with which our public discourse is most comfortable: depoliticised, universally adored, a man-sized Paddington Bear fit only for our veneration. Who teaches us about tree frogs and seal cubs and stick insects and asks for nothing in return. And perhaps there are more difficult questions to negotiate here: the extent to which he has been a force for the meaningful and revolutionary change he seeks, and the extent to which his broad, inoffensive appeal has been more hindrance than help, allowing the powerful to feign concern for the planet while shirking the tough and bloody compromises required to secure it.

Personally, I'm inclined to give Attenborough the benefit of the doubt on this. At heart, he has always been a journalist rather than a scientist, aware above all of the importance of meeting the audience where they are, rather than where he would like them to be. His programmes have always focused from first principles on the beauty and fascination of the natural world, depicting conservation as an act of conscience rather than sacrifice.

For a "standard, boring leftwing liberal", as he once described himself, Attenborough has always understood the importance of spectacle over polemic. Show trumps tell every time. And while there remains a sizeable minority on the anti-net-zero right that has unsuccessfully tried to turn him into a hate figure, he remains trusted and credible, perhaps even the only eco-socialist in Britain whom the rightwing press hasn't tried to hound out of a job.

What we get, instead, is the fat-free Attenborough, an Attenborough shorn of all his activist instincts, his many prescient diagnoses of where humanity has gone wrong. Perhaps, on reflection, it is no surprise that he is followed wherever he goes with the sound of applause and fanfares. It saves us the trouble of hearing what he actually says.""",

        "annotations_vocab": [
            {"word": "curbed", "phonetic": "/kɜːbd/", "pos": "v.", "definition": "restrained or kept in check", "chinese": "抑制，控制",
             "linguistics": "来自 curb（路缘石/马嚼子）。原义：用马嚼子勒住马 = 控制。引申为「限制、抑制」。注意双义：curb 作名词是「路缘石」（美式），kerb 是英式拼写。动词义全球通用。",
             "usage": "通用词。口语替代：control / limit / hold back / rein in。搭配：curb spending / inflation / enthusiasm / emissions / excesses。",
             "examples": [{"text": "The central bank raised interest rates to curb inflation.", "source": "Financial Times, 2023"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "pilfered", "phonetic": "/ˈpɪl.fəd/", "pos": "v.", "definition": "stolen (especially things of small value)", "chinese": "偷窃，顺手牵羊",
             "linguistics": "古法语 pelfrer（掠夺）。比 steal 更轻描淡写，通常指小偷小摸。在本文中是幽默用法——作者「偷」了别人的话来引用。三个近义词连用（pilfered, purloined, shoplifted）构成修辞递进。",
             "usage": "半正式，常带幽默色彩。口语替代：stolen / nicked / pinched / taken。搭配：pilfered from / pilfered goods / petty pilfering。",
             "examples": [{"text": "Someone had pilfered the biscuits from the staff kitchen.", "source": "Collins English Dictionary"}],
             "level": "IELTS 7.5+"},
            {"word": "purloined", "phonetic": "/pɜːˈlɔɪnd/", "pos": "v.", "definition": "stolen; taken dishonestly", "chinese": "窃取，盗用",
             "linguistics": "古法语 purloigner（放远处），pur-（= pro- 向前）+ loigner（远离）。字面义「把东西拿到远处」= 偷走。比 steal 更文学化。爱伦·坡的经典短篇 The Purloined Letter（《失窃的信》）让这个词广为人知。",
             "usage": "书面文学用语。口语中几乎不用，说 stolen / taken。在本文中与 pilfered、shoplifted 并列使用制造幽默效果。",
             "examples": [{"text": "The precious manuscript had been purloined from the archive.", "source": "Oxford English Dictionary"}],
             "level": "TEM-8 / IELTS 8.0+"},
            {"word": "erudite", "phonetic": "/ˈer.ʊ.daɪt/", "pos": "adj.", "definition": "having or showing great knowledge or learning", "chinese": "博学的，学识渊博的",
             "linguistics": "拉丁语 erudire（教育），e-（出）+ rudis（粗糙的/未加工的）。字面义「从粗糙状态中打磨出来」= 经过深度教育的。比 knowledgeable 或 learned 更高级、更正式。",
             "usage": "书面正式。口语替代：very knowledgeable / well-read / scholarly / brainy。搭配：erudite scholar / discussion / analysis / reference。",
             "examples": [{"text": "She is one of the most erudite commentators on modern art.", "source": "The New Yorker, 2022"}],
             "level": "TEM-8 / IELTS 8.0+"},
            {"word": "incendiary", "phonetic": "/ɪnˈsen.di.er.i/", "pos": "adj.", "definition": "tending to cause strong anger or controversy; inflammatory", "chinese": "煽动性的，引发争议的",
             "linguistics": "拉丁语 incendere（点火），in-（进入）+ candere（发光/燃烧）。双义词：① 字面义「纵火的」（incendiary device = 燃烧弹）② 比喻义「煽动性的」（incendiary speech = 煽动性言论）。与 incense（激怒/香）同源。",
             "usage": "半正式。口语替代：provocative / inflammatory / controversial / stirring up trouble。搭配：incendiary remarks / rhetoric / speech / language。",
             "examples": [{"text": "The politician's incendiary remarks sparked widespread protests.", "source": "BBC News, 2023"}],
             "level": "TEM-8 / IELTS 7.5+"},
            {"word": "firebrand", "phonetic": "/ˈfaɪə.brænd/", "pos": "n.", "definition": "a person who is passionate about a particular cause, often controversial", "chinese": "煽动者，激进分子",
             "linguistics": "fire（火）+ brand（= 燃烧的木头）。字面义「燃烧的木棍」。比喻义「到处点火的人」= 激进活动家。与 incendiary 的「火」意象一致。在本文中是反讽——作者故意用耸人听闻的词来形容阿滕伯勒，制造意外感。",
             "usage": "半正式。口语替代：radical / agitator / troublemaker / activist。搭配：political firebrand / leftwing firebrand。",
             "examples": [{"text": "As a young firebrand, she led protests against corporate pollution.", "source": "The Guardian, 2022"}],
             "level": "IELTS 7.5+"},
            {"word": "seismic", "phonetic": "/ˈsaɪz.mɪk/", "pos": "adj.", "definition": "of enormous proportions or effect; earth-shaking", "chinese": "地震般的，影响巨大的",
             "linguistics": "希腊语 seismos（地震）。字面义「与地震有关的」（seismic activity）。比喻义「影响巨大到像地震一样」。类似从自然灾害借来的比喻词：volcanic（火山般的）、tidal（潮汐般的）、tsunami（海啸般的）。",
             "usage": "半正式。口语替代：massive / enormous / game-changing / earth-shattering。搭配：seismic shift / change / impact / event。",
             "examples": [{"text": "The ruling represented a seismic shift in legal precedent.", "source": "The New York Times, 2023"}],
             "level": "IELTS 7.5+"},
            {"word": "utopian", "phonetic": "/juːˈtəʊ.pi.ən/", "pos": "adj.", "definition": "idealistic but impractical; envisioning a perfect society", "chinese": "乌托邦式的，空想的",
             "linguistics": "来自 Thomas More 1516 年的著作 Utopia（乌托邦）。希腊语 ou-（不/无）+ topos（地方）= 「不存在的地方」。More 故意造了一个双关词：也可读作 eu-topos（好地方）。utopian 既可褒义（理想主义的）也可贬义（不切实际的）。",
             "usage": "半正式。口语替代：idealistic / unrealistic / pie in the sky / too good to be true。搭配：utopian vision / dream / ideal / society。反义词：dystopian（反乌托邦的）。",
             "examples": [{"text": "Critics dismissed the plan as utopian and unachievable.", "source": "The Economist, 2023"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "railed", "phonetic": "/reɪld/", "pos": "v.", "definition": "complained or protested strongly and bitterly", "chinese": "强烈抨击，怒斥",
             "linguistics": "可能来自法语 railler（嘲弄）。rail at/against = 对……大声抱怨/抨击。比 complain 更强烈，暗示愤怒和激烈的言辞。注意与 rail（栏杆/铁轨）是不同的词源。",
             "usage": "半正式。口语替代：complained loudly / lashed out at / attacked / blasted。搭配：rail against / at injustice / the system / corruption。",
             "examples": [{"text": "Activists railed against the government's environmental policies.", "source": "The Guardian, 2023"}],
             "level": "IELTS 7.0+"},
            {"word": "extractive", "phonetic": "/ɪkˈstræk.tɪv/", "pos": "adj.", "definition": "involving the removal of natural resources; exploitative", "chinese": "攫取性的，榨取式的",
             "linguistics": "extract（提取）+ -ive。原义「提取资源的」（extractive industries = 采矿业/石油业）。近年被经济学家扩展使用：extractive capitalism = 只顾攫取利润、不回馈社会的资本主义。与 inclusive（包容的）形成对立。",
             "usage": "正式用语。口语替代：exploitative / taking without giving back / draining。搭配：extractive capitalism / industries / institutions / economy。",
             "examples": [{"text": "Many developing countries remain trapped in extractive economic models.", "source": "Foreign Affairs, 2023"}],
             "level": "IELTS 7.5+"},
            {"word": "shrill", "phonetic": "/ʃrɪl/", "pos": "adj.", "definition": "high-pitched and piercing; (figuratively) urgent and insistent", "chinese": "尖锐的，刺耳的（比喻：急切的，强烈的）",
             "linguistics": "古英语 scrallian（大声叫喊）。双义词：① 声音尖锐刺耳 ② 比喻「言辞激烈、让人不舒服」。本文中 in increasingly shrill terms = 用越来越急切/激烈的措辞。注意 shrill 用于形容女性声音时可能带有性别歧视意味。",
             "usage": "半正式。口语替代：loud / piercing / urgent / increasingly desperate。搭配：shrill voice / tone / warning / cry / criticism。",
             "examples": [{"text": "His warnings about the economic downturn grew increasingly shrill.", "source": "Financial Times, 2023"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "reconcile", "phonetic": "/ˈrek.ən.saɪl/", "pos": "v.", "definition": "to make two apparently conflicting things compatible or consistent", "chinese": "调和，使一致",
             "linguistics": "拉丁语 reconciliare（恢复友好），re-（再次）+ conciliare（结合）。三个义项：① 调和矛盾 ② 和解（reconcile with someone）③ 接受（reconcile oneself to sth）。本文用义项①。",
             "usage": "半正式。口语替代：square / match / make sense of / bring together。搭配：reconcile differences / conflicting views / the evidence with the theory。",
             "examples": [{"text": "It is difficult to reconcile his public image with his private behaviour.", "source": "The Atlantic, 2023"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "feted", "phonetic": "/ˈfeɪ.tɪd/", "pos": "v.", "definition": "honoured and entertained lavishly", "chinese": "被盛大欢迎的，被隆重招待的",
             "linguistics": "法语 fêter（庆祝），fête（节日/庆典）。比 celebrated 更强调「奢华、隆重」的庆祝场面。注意发音是 /feɪt/，不要读成 /fiːt/（那是 feat 的发音）。",
             "usage": "书面正式。口语替代：celebrated / honoured / praised / made a fuss of。搭配：feted by the media / critics / the public。",
             "examples": [{"text": "The author was feted at literary festivals across Europe.", "source": "The New Yorker, 2023"}],
             "level": "TEM-8 / IELTS 7.5+"},
            {"word": "benedictions", "phonetic": "/ˌben.ɪˈdɪk.ʃənz/", "pos": "n.", "definition": "expressions of good wishes; blessings", "chinese": "祝福，赞美之辞",
             "linguistics": "拉丁语 benedictio（祝福），bene-（好）+ dicere（说）。字面义「说好话」。bene- 前缀系列：benefit（利益）、benevolent（仁慈的）、benefactor（恩人）。反义前缀 male-/mal-：malevolent（恶意的）、malediction（诅咒）。",
             "usage": "高度书面正式。口语替代：blessings / good wishes / praise / warm words。主要用于宗教或文学语境。",
             "examples": [{"text": "The priest offered a final benediction before the congregation departed.", "source": "Oxford English Dictionary"}],
             "level": "TEM-8 / IELTS 8.0+"},
            {"word": "bromides", "phonetic": "/ˈbrəʊ.maɪdz/", "pos": "n.", "definition": "trite and unoriginal remarks or ideas; platitudes", "chinese": "陈词滥调，老生常谈",
             "linguistics": "原义：溴化物（化学药品，19 世纪用作镇静剂）。引申为「令人昏昏欲睡的无聊话」= 陈词滥调。这个比喻很巧妙：bromide 让人犯困，bromides（老话套话）同样让人无聊到打瞌睡。",
             "usage": "书面正式。口语替代：clichés / platitudes / empty words / same old stuff。搭配：vague bromides / political bromides / tired bromides。",
             "examples": [{"text": "The speech was full of bromides about unity and progress, but lacked any concrete proposals.", "source": "The Economist, 2023"}],
             "level": "TEM-8 / IELTS 8.0+"},
            {"word": "veneration", "phonetic": "/ˌven.əˈreɪ.ʃən/", "pos": "n.", "definition": "great respect or reverence", "chinese": "崇敬，尊崇",
             "linguistics": "拉丁语 venerari（崇拜）。与 Venus（维纳斯/爱神）可能同源。比 respect 更强——veneration 接近于「崇拜」的程度。在宗教语境中指对圣人的敬拜（不及 worship 的程度）。",
             "usage": "书面正式。口语替代：deep respect / admiration / worship / awe。搭配：an object of veneration / held in veneration / public veneration。",
             "examples": [{"text": "The temple is a place of veneration for millions of pilgrims.", "source": "National Geographic, 2022"}],
             "level": "TEM-8 / IELTS 8.0+"},
            {"word": "hindrance", "phonetic": "/ˈhɪn.drəns/", "pos": "n.", "definition": "a thing that provides resistance or obstruction; an impediment", "chinese": "障碍，妨碍",
             "linguistics": "hinder（阻碍）+ -ance（名词后缀）。比 obstacle 更强调「妨碍进程」而非「物理阻挡」。常用句型：more of a hindrance than a help（帮倒忙/弊大于利）——这正是本文使用的句式。",
             "usage": "半正式。口语替代：obstacle / problem / getting in the way / nuisance。搭配：more hindrance than help / without hindrance / a hindrance to progress。",
             "examples": [{"text": "Excessive regulation can be a hindrance to small business growth.", "source": "Financial Times, 2023"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "feign", "phonetic": "/feɪn/", "pos": "v.", "definition": "to pretend to feel or have (an emotion, quality, or illness)", "chinese": "假装，佯装",
             "linguistics": "拉丁语 fingere（塑造/假装）。与 fiction（小说/虚构）、figment（虚构之物）、feint（佯攻）同源。feign 比 pretend 更正式，且通常暗含欺骗的负面意味。",
             "usage": "书面正式。口语替代：pretend / fake / put on / act like。搭配：feign surprise / ignorance / concern / interest / illness。",
             "examples": [{"text": "She feigned interest in his story while checking her phone.", "source": "Collins English Dictionary"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"word": "polemic", "phonetic": "/pəˈlem.ɪk/", "pos": "n.", "definition": "a strong verbal or written attack or argument", "chinese": "论战，激烈的批判",
             "linguistics": "希腊语 polemos（战争）。polemic = 文字上的「战争」= 激烈的争论性文章/演讲。polemical（adj. 好争论的）。注意与 political（政治的）虽然看起来像但词源完全不同。",
             "usage": "书面正式。口语替代：attack / argument / rant / takedown。搭配：political polemic / a polemic against / polemical writing。",
             "examples": [{"text": "The essay was less a balanced analysis than a polemic against globalisation.", "source": "The Economist, 2023"}],
             "level": "TEM-8 / IELTS 7.5+"},
            {"word": "credible", "phonetic": "/ˈkred.ɪ.bəl/", "pos": "adj.", "definition": "able to be believed or trusted; convincing", "chinese": "可信的，有说服力的",
             "linguistics": "拉丁语 credere（相信）。cred- 词根系列：credit（信用）、incredible（难以置信的）、credentials（资历/证书）、creed（信条）。credible 比 believable 更正式。",
             "usage": "通用词。口语替代：believable / trustworthy / reliable / convincing。搭配：credible source / threat / evidence / candidate / witness。",
             "examples": [{"text": "The report relies on credible sources and verified data.", "source": "Nature, 2023"}],
             "level": "CET-6 / IELTS 6.5+"},
            {"word": "hound", "phonetic": "/haʊnd/", "pos": "v.", "definition": "to harass, pursue relentlessly", "chinese": "追逼，骚扰",
             "linguistics": "来自 hound（猎犬）。动词化后意为「像猎犬追猎物一样追赶/骚扰某人」。hound sb out of sth = 通过持续骚扰迫使某人离开（工作/职位等）。英语中很多动物名词都可以动词化：badger（纠缠）、fox（迷惑）、parrot（鹦鹉学舌）。",
             "usage": "半正式。口语替代：harass / chase / persecute / force out。搭配：hound sb out of office / a job / the country。",
             "examples": [{"text": "She was hounded out of her position by a relentless media campaign.", "source": "The Guardian, 2023"}],
             "level": "IELTS 7.0+"},
            {"word": "shorn", "phonetic": "/ʃɔːn/", "pos": "adj.", "definition": "stripped of; deprived of", "chinese": "被剥夺的，被去掉的",
             "linguistics": "shear（剪）的过去分词。原义「被剪掉毛的」（如羊毛被剪）。引申为「被剥夺的」。shorn of = 失去了/被去掉了。这个词非常有画面感——想象一只被剪光毛的羊，赤裸裸地站着。",
             "usage": "书面文学用语。口语替代：stripped of / without / lacking / left with nothing。搭配：shorn of its power / dignity / meaning / context。",
             "examples": [{"text": "The building, shorn of its decorative elements, looked strangely bare.", "source": "The New Yorker, 2022"}],
             "level": "TEM-8 / IELTS 8.0+"},
            {"word": "prescient", "phonetic": "/ˈpres.i.ənt/", "pos": "adj.", "definition": "having or showing knowledge of events before they take place", "chinese": "有先见之明的，预知的",
             "linguistics": "拉丁语 praescire（预知），prae-（之前）+ scire（知道）。与 science（科学 = 知识）同根。prescient 比 farsighted 更强——不仅看得远，而且准确预测了未来。",
             "usage": "书面正式。口语替代：ahead of his time / saw it coming / prophetic / visionary。搭配：prescient warning / analysis / observation / prediction。",
             "examples": [{"text": "Her prescient analysis of the housing market proved remarkably accurate.", "source": "Financial Times, 2023"}],
             "level": "TEM-8 / IELTS 8.0+"},
            {"word": "fanfares", "phonetic": "/ˈfæn.feəz/", "pos": "n.", "definition": "short showy pieces of music played on brass instruments; great attention or activity", "chinese": "号角声，大张旗鼓的欢迎",
             "linguistics": "法语 fanfare（喇叭齐鸣）。原义：庆典上的铜管乐队演奏。引申为「大肆宣传/张扬的欢迎」。without fanfare = 低调地（反义）。在本文中暗含讽刺：大家用掌声和号角掩盖了阿滕伯勒真正想说的话。",
             "usage": "半正式。口语替代：big welcome / fuss / celebration / hype。搭配：amid much fanfare / without fanfare / a fanfare of publicity。",
             "examples": [{"text": "The product was launched with great fanfare but disappointing sales.", "source": "The Economist, 2023"}],
             "level": "IELTS 7.0+"},
            {"word": "mournful", "phonetic": "/ˈmɔːn.fəl/", "pos": "adj.", "definition": "feeling or expressing sadness, grief, or sorrow", "chinese": "悲伤的，哀悼的",
             "linguistics": "mourn（哀悼）+ -ful（充满……的）。mourn 来自古英语 murnan（忧伤）。注意 mourn 既可以是及物的（mourn sb = 哀悼某人）也可以是不及物的（mourn for/over sth）。-ful 后缀系列：sorrowful, cheerful, hopeful, dreadful。",
             "usage": "半正式，文学性较强。口语替代：sad / gloomy / sorrowful / melancholy。搭配：mournful music / expression / tone / cry。",
             "examples": [{"text": "The mournful sound of the cello filled the empty concert hall.", "source": "The Guardian, 2023"}],
             "level": "CET-6 / IELTS 7.0+"},
        ],

        "annotations_phrases": [
            {"phrase": "a far cry from", "definition": "completely different from; nothing like", "chinese": "与……截然不同，相去甚远",
             "linguistics": "起源有争议，可能来自苏格兰语「在喊叫声能传到的范围之外」。表示两事物之间差距巨大。经济学人和卫报都频繁使用这个表达。",
             "usage": "半正式，写作口语皆可。口语替代：nothing like / worlds apart from / totally different from。雅思写作：The reality is a far cry from what was promised.",
             "examples": [{"text": "The final product was a far cry from the original design.", "source": "The Economist, 2023"}],
             "level": "CET-6 / IELTS 6.5+"},
            {"phrase": "cast to the margins", "definition": "pushed to the edges of society or relevance; marginalised", "chinese": "被边缘化，被排挤到边缘",
             "linguistics": "cast（抛掷）+ to the margins（到边缘）。与 marginalise 同义但更生动——用了「扔」这个动作。margin 原义「页边空白」，引申为「社会边缘」。搭配：pushed to the margins / live on the margins。",
             "usage": "书面正式。口语替代：pushed aside / sidelined / ignored / left out。搭配：cast to the margins of society / discourse / cultural life。",
             "examples": [{"text": "Indigenous voices have long been cast to the margins of political debate.", "source": "The Guardian, 2022"}],
             "level": "IELTS 7.0+"},
            {"phrase": "banging on about", "definition": "talking repeatedly and boringly about something", "chinese": "喋喋不休地谈论",
             "linguistics": "非正式英式英语。bang on（= 反复敲打）比喻「反复唠叨同一件事」。带有轻微的负面含义——暗示对方说得太多了。在本文中是自嘲式的用法：作者用贬义词来描述阿滕伯勒多年来坚持警告气候危机，实际上是在褒扬他的坚持。",
             "usage": "非正式，口语色彩浓。口语替代：going on about / talking non-stop about / harping on about。正式替代：repeatedly warning about / persistently advocating for。",
             "examples": [{"text": "He's always banging on about the importance of recycling.", "source": "Collins English Dictionary"}],
             "level": "IELTS 7.0+ (非正式)"},
            {"phrase": "in jest", "definition": "as a joke; not seriously", "chinese": "开玩笑地，戏谑地",
             "linguistics": "jest（玩笑），来自古法语 geste（行为/故事）。in jest = 以开玩笑的方式。对比：in earnest（认真地）。Many a true word is spoken in jest（笑话中往往有真话）是经典谚语。",
             "usage": "半正式。口语替代：as a joke / jokingly / not seriously / tongue in cheek。搭配：said in jest / meant in jest / only partly in jest。",
             "examples": [{"text": "The remark was made in jest, but it contained a grain of truth.", "source": "Oxford Dictionary of Idioms"}],
             "level": "CET-6 / IELTS 7.0+"},
            {"phrase": "the benefit of the doubt", "definition": "a favourable judgement given despite uncertainty or suspicion", "chinese": "疑罪从无，善意推定",
             "linguistics": "法律术语起源：当证据不确定时，给被告有利的推定。生活中用法：在没有确凿证据的情况下，选择信任某人。give sb the benefit of the doubt = 姑且相信某人。",
             "usage": "通用，写作口语皆可。口语替代：trust them / take their word for it / assume the best。搭配：give sb the benefit of the doubt / deserve the benefit of the doubt。",
             "examples": [{"text": "I'll give him the benefit of the doubt and assume he didn't mean to offend.", "source": "Cambridge Dictionary"}],
             "level": "CET-6 / IELTS 6.5+"},
            {"phrase": "from first principles", "definition": "based on fundamental truths or axioms rather than assumptions", "chinese": "从基本原理出发，从头开始推导",
             "linguistics": "源自亚里士多德哲学。first principles = 最基本的、不可再分解的真理/公理。Elon Musk 让这个短语在科技界广为流传——first principles thinking = 不依赖假设和类比，从最基础的事实出发推理。",
             "usage": "半正式。口语替代：from scratch / from the ground up / from the basics / going back to basics。搭配：think from first principles / reasoning from first principles。",
             "examples": [{"text": "Instead of copying competitors, the team designed the product from first principles.", "source": "Harvard Business Review, 2023"}],
             "level": "IELTS 7.0+"},
            {"phrase": "show trumps tell", "definition": "demonstrating something is more effective than merely describing it", "chinese": "展示胜过讲述（行动胜于言辞）",
             "linguistics": "改编自写作教学中的经典原则 show, don't tell（展示，不要讲述）。trump 在这里是动词，意为「胜过」（来自纸牌游戏中的王牌 trump card）。整句话的意思是：用画面和事实展示比用言语说教更有效。",
             "usage": "半正式。口语替代：actions speak louder than words / showing is better than telling / demonstrate, don't just talk。",
             "examples": [{"text": "In documentary filmmaking, show always trumps tell.", "source": "BBC Film Academy, 2023"}],
             "level": "IELTS 7.0+"},
            {"phrase": "at heart", "definition": "in one's true nature; fundamentally", "chinese": "本质上，内心深处",
             "linguistics": "heart 在英语中象征一个人最真实的自我。at heart = 在本质上/骨子里。类似表达：at the core / deep down / fundamentally。He's a journalist at heart = 他骨子里是个记者（即使他可能也做其他事情）。",
             "usage": "通用。口语中非常常见。搭配：at heart, he is... / she's a scientist at heart / young at heart。",
             "examples": [{"text": "Despite his success in business, he remains an artist at heart.", "source": "The New Yorker, 2022"}],
             "level": "CET-4 / IELTS 6.0+"},
            {"phrase": "meet the audience where they are", "definition": "to communicate in a way that matches the audience's current level of understanding", "chinese": "在受众所在的位置与他们对接（用受众能理解的方式沟通）",
             "linguistics": "教育学和传播学术语。不是要求受众来适应你的水平，而是你去适应受众的水平。体现了一种以受众为中心的传播哲学。与中文的「因材施教」有异曲同工之妙。",
             "usage": "半正式，教育和传播领域常用。口语替代：speak their language / connect with them on their level / don't talk down to them / start where they are。",
             "examples": [{"text": "Good teachers meet their students where they are, not where they think they should be.", "source": "Harvard Education Review, 2022"}],
             "level": "IELTS 7.0+"},
            {"phrase": "the fat-free Attenborough", "definition": "a version stripped of all substance, leaving only the bland surface", "chinese": "「脱脂版」阿滕伯勒（被去掉了一切实质内容的版本）",
             "linguistics": "fat-free 原义「脱脂的」（如脱脂牛奶）。在这里是创造性比喻：就像脱脂食品去掉了脂肪（也去掉了风味），公众只接受了去掉了政治立场（也去掉了真实观点）的阿滕伯勒。这种将食品术语用于社会批评的修辞非常巧妙。",
             "usage": "这是作者的独创表达，不是固定短语。但 X-free 这个构词模式非常常见：sugar-free（无糖的）、stress-free（无压力的）、risk-free（无风险的）。用于修辞时可以创造意外效果。",
             "examples": [{"text": "What voters want is substance, not the fat-free version of politics.", "source": "原文改编"}],
             "level": "IELTS 7.5+ (修辞理解)"},
        ],

        "annotations_sentences": [
            {"sentence": "In fact, they were pilfered, purloined, shoplifted from a far more erudite radical thinker than myself.",
             "highlight_key": "In fact, they were pilfered, purloined, shoplifted from a far more erudite radical thinker than myself",
             "translation": "事实上，它们是从一位比我博学得多的激进思想家那里偷来的、窃取的、顺手牵羊拿走的。",
             "breakdown": "三个近义词 pilfered, purloined, shoplifted 构成渐强排比——从文学化的「偷」到日常口语的「顺」。这种修辞叫 tricolon（三段并列），增强节奏感和幽默效果。a far more erudite radical thinker than myself 是谦虚的自贬——作者暗示大卫·阿滕伯勒比自己激进得多。",
             "grammar_points": ["三个近义动词并列（tricolon 修辞）", "被动语态 were pilfered", "a far more + adj. + than = 比……得多"],
             "writing_tip": "三词并列是英语修辞的经典手法。三个词从不同角度描述同一件事，产生韵律感和戏剧效果。示例：The project was delayed, derailed, and ultimately abandoned."},
            {"sentence": "At the very least, you would probably assume that, in the current climate, anyone daring to utter these dangerous fringe sentiments would be cast to the margins of our cultural life.",
             "highlight_key": "anyone daring to utter these dangerous fringe sentiments would be cast to the margins of our cultural life",
             "translation": "你至少会认为，在当前的氛围下，任何胆敢说出这些危险的边缘观点的人都会被推到我们文化生活的边缘。",
             "breakdown": "At the very least（至少）→ you would probably assume that（你大概会认为）→ in the current climate（在当前形势下——climate 这里不是「气候」而是「氛围」）→ anyone daring to utter（任何胆敢说出的人——现在分词做定语）→ these dangerous fringe sentiments（这些危险的边缘观点）→ would be cast to the margins（会被扔到边缘）。",
             "grammar_points": ["climate 的比喻用法：政治/社会氛围", "daring to 现在分词做后置定语 = who dares to", "would be cast 虚拟语气", "margins 与 fringe 形成呼应"],
             "writing_tip": "In the current climate 是新闻写作高频表达，指「在当前的社会/政治氛围下」。雅思示例：In the current climate of political polarisation, moderate voices struggle to be heard."},
            {"sentence": "The beloved 100-year-old television naturalist, often cited in polls as the most trusted man in the country, was also the man who advocated for seismic global financial redistribution.",
             "highlight_key": "The beloved 100-year-old television naturalist, often cited in polls as the most trusted man in the country, was also the man who advocated for seismic global financial redistribution",
             "translation": "这位深受爱戴的百岁电视自然学家——常在民调中被评为全国最受信赖的人——同时也是那个倡导全球金融体系进行地震般重新分配的人。",
             "breakdown": "主句很简单：The naturalist was also the man who...（这位自然学家也是那个……的人）。关键是插入语：often cited in polls as the most trusted man in the country（常在民调中被引用为最受信赖的人）。这个插入语制造了反差：最受信赖 vs 最激进。seismic（地震般的）修饰 redistribution（重新分配）加强了冲击力。",
             "grammar_points": ["同位语/插入语放在逗号之间", "often cited 过去分词做后置定语", "advocate for + 名词 = 倡导", "seismic 作为比喻修饰词"],
             "writing_tip": "在主语和谓语之间插入描述性短语来制造反差是非常高级的写作技巧。模板：The X, widely known as Y, was actually Z."},
            {"sentence": "He was banging on about the dangers of mass consumption, extractive capitalism and the miseries of the market economy long before Blue Planet II set footage of a plastic-choked pilot whale to mournful music.",
             "highlight_key": "He was banging on about the dangers of mass consumption, extractive capitalism and the miseries of the market economy long before Blue Planet II",
             "translation": "早在《蓝色星球II》将一只被塑料窒息的领航鲸的画面配上悲伤音乐之前，他就已经在喋喋不休地谈论大规模消费的危险、榨取式资本主义和市场经济的苦难了。",
             "breakdown": "He was banging on about（他在喋喋不休地谈论——非正式动词短语，制造口语化的亲切感）→ three-part list: mass consumption, extractive capitalism, the miseries of the market economy（三段并列）→ long before（早在……之前——时间状语从句）→ Blue Planet II set footage to mournful music（《蓝色星球II》将画面配上悲伤音乐）。",
             "grammar_points": ["was banging on about 过去进行时表持续动作", "三个名词短语并列", "long before + 从句 = 早在……之前", "set X to Y = 将 X 配上 Y"],
             "writing_tip": "long before X did Y, Z had already been doing W 这个时间对比句式适合强调先见之明。雅思示例：Scientists were warning about climate change long before it became a mainstream political issue."},
            {"sentence": "A galaxy of celebrities was wheeled out to deliver warm benedictions.",
             "highlight_key": "A galaxy of celebrities was wheeled out to deliver warm benedictions",
             "translation": "一群明星被推出来发表温暖的祝福之辞。",
             "breakdown": "短句但信息密度极高。a galaxy of（一「银河系」的——量词比喻：形容名人多得像星星）→ celebrities was wheeled out（被推出来——wheel out 原义「推出展示品」，暗示名人像道具一样被使用）→ to deliver warm benedictions（来发表温暖的祝福——deliver 使「祝福」变成了表演而非真情）。每个词都带有暗讽。",
             "grammar_points": ["a galaxy of = 一大群（比喻量词）", "was wheeled out 被动语态暗示被利用", "deliver 用于 benedictions 暗示表演性质"],
             "writing_tip": "使用比喻性量词（a galaxy of / a tsunami of / an avalanche of）可以让表达更生动。但注意选择与语境匹配的比喻——a galaxy of celebrities 完美呼应了「明星」的双关。"},
            {"sentence": "This is, of course, the Attenborough with which our public discourse is most comfortable: depoliticised, universally adored, a man-sized Paddington Bear fit only for our veneration.",
             "highlight_key": "This is, of course, the Attenborough with which our public discourse is most comfortable: depoliticised, universally adored, a man-sized Paddington Bear fit only for our veneration",
             "translation": "这当然就是我们的公共话语最能接受的那个阿滕伯勒：去政治化的、被所有人喜爱的、一个只配被我们崇敬的真人大小的帕丁顿熊。",
             "breakdown": "主句：This is the Attenborough → with which our public discourse is most comfortable（定语从句：我们的公共话语最能接受的）→ 冒号后展开三个并列描述：① depoliticised（被去政治化的）② universally adored（被所有人喜爱的）③ a man-sized Paddington Bear fit only for our veneration（一个真人大小的帕丁顿熊，只配被崇拜）。第三个描述是讽刺高潮。",
             "grammar_points": ["with which 是 comfortable with 的介词前置", "冒号后三个并列成分形成渐强", "fit only for = 只适合/只配", "过去分词做形容词：depoliticised, adored"],
             "writing_tip": "冒号后用三个并列形容词/短语展开描述是精彩的修辞。每个成分可以逐渐增强，最后一个是高潮/转折。"},
            {"sentence": "And perhaps there are more difficult questions to negotiate here: the extent to which he has been a force for the meaningful and revolutionary change he seeks, and the extent to which his broad, inoffensive appeal has been more hindrance than help.",
             "highlight_key": "the extent to which his broad, inoffensive appeal has been more hindrance than help",
             "translation": "也许这里有更难回答的问题：他在多大程度上推动了他所追求的有意义的、革命性的变革，以及他广泛的、无害的吸引力在多大程度上是帮倒忙了。",
             "breakdown": "主句：there are more difficult questions to negotiate（有更难商讨的问题）→ 冒号展开两个并列的 the extent to which 从句：① ...he has been a force for change（他是否推动了变革）② ...his appeal has been more hindrance than help（他的吸引力是否帮了倒忙）。两个 the extent to which 形成对称的平行结构，探讨一个核心悖论。",
             "grammar_points": ["the extent to which = 在多大程度上（高级名词性从句引导词）", "more X than Y 比较结构", "negotiate 在这里指「处理/应对」而非「谈判」"],
             "writing_tip": "the extent to which 是学术写作中最有用的句式之一，表示「在多大程度上」。雅思示例：The extent to which technology improves education depends on how it is implemented."},
            {"sentence": "Perhaps, on reflection, it is no surprise that he is followed wherever he goes with the sound of applause and fanfares. It saves us the trouble of hearing what he actually says.",
             "highlight_key": "Perhaps, on reflection, it is no surprise that he is followed wherever he goes with the sound of applause and fanfares",
             "translation": "也许，经过反思，他走到哪里都被掌声和号角声环绕并不令人意外。这省去了我们倾听他真正想说什么的麻烦。",
             "breakdown": "两句话构成一个精妙的结尾。第一句：on reflection（经过反思）→ it is no surprise that（不足为奇的是）→ he is followed wherever he goes（无论走到哪里都被跟随）→ with the sound of applause and fanfares（伴随掌声和号角）。第二句是致命一击：It saves us the trouble of hearing what he actually says（这让我们不必费心去听他实际上在说什么）。掌声不是敬意——是掩盖真相的噪音。",
             "grammar_points": ["on reflection = 经过反思", "it is no surprise that 主语从句", "wherever he goes 让步状语从句", "save sb the trouble of = 免去某人的麻烦"],
             "writing_tip": "文章结尾用两句话：第一句铺垫，第二句反转——这是专栏写作中最有力的收尾方式。最后一句简短有力，留给读者回味的空间。"},
        ],
    },
]
